# Generated by Django 5.1 on 2024-08-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
    ]
